from __future__ import annotations
from datetime import datetime, timezone
from app.models.formula import AIAnalysisResult, SafetyGateResult


def generate_markdown_report(
    formula_name: str,
    atom_ids: list[str],
    atoms: list[dict],
    analysis: AIAnalysisResult,
    safety: SafetyGateResult,
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    status_emoji = {"Green": "✅", "Yellow": "⚠️", "Red": "🔴", "Black": "⛔"}.get(
        analysis.safety_status, "❓"
    )
    evidence_level = getattr(safety, "evidence_level", analysis.evidence_level or "E0")

    lines: list[str] = []

    # ── ヘッダー ───────────────────────────────────────────────────────────────
    lines += [
        f"# {analysis.formula_name or formula_name}",
        "",
        f"> Generated by Formula Fuse Studio — {now}",
        "",
        "---",
        "",
    ]

    # ── 1. 使用 Atom 一覧 ──────────────────────────────────────────────────────
    lines += ["## 使用 Atom", ""]
    for atom in atoms:
        gras = atom.get("gras", {})
        gras_status = gras.get("status", "")
        gras_icon = {"GRAS": "🟢", "NDI": "🟡", "food_additive": "🔵", "unknown": "❓"}.get(gras_status, "")
        lines.append(
            f"- **{atom['name_ja']}** ({atom['name_en']})  "
            f"`{atom['atom_type']}`  {gras_icon} {gras_status or '—'}"
        )
    lines.append("")

    # ── 2. Formula 概要 ────────────────────────────────────────────────────────
    lines += [
        "---",
        "",
        "## Formula 概要",
        "",
        analysis.formula_summary or "（未生成）",
        "",
        "## 期待される機能",
        "",
        analysis.expected_function or "（未生成）",
        "",
        "## メカニズム仮説",
        "",
        analysis.mechanism_hypothesis or "（未生成）",
        "",
        "---",
        "",
    ]

    # ── 3. Safety Gate ─────────────────────────────────────────────────────────
    lines += [
        f"## Safety Status: {status_emoji} {analysis.safety_status}",
        "",
        f"**Evidence Level: {evidence_level}**",
        "",
    ]

    if safety.blocking_reasons:
        lines += ["### ブロック理由", ""]
        for r in safety.blocking_reasons:
            lines.append(f"- 🚫 {r}")
        lines.append("")

    if analysis.risk_notes:
        lines += ["### リスクノート", ""]
        for note in analysis.risk_notes:
            lines.append(f"- {note}")
        lines.append("")

    gras_notes = getattr(safety, "gras_notes", [])
    if gras_notes:
        lines += ["### GRAS / 規制上の注意", ""]
        for note in gras_notes:
            lines.append(f"- ⚠️ {note}")
        lines.append("")

    if safety.required_expert_reviews:
        lines += ["### 専門家確認事項", ""]
        for r in safety.required_expert_reviews:
            lines.append(f"- 👤 {r}")
        lines.append("")

    lines += ["---", ""]

    # ── 4. Bond 解釈 ───────────────────────────────────────────────────────────
    if analysis.bond_interpretation:
        lines += ["## Bond 解釈", ""]
        for bond in analysis.bond_interpretation:
            lines.append(f"### {bond.bond_type}")
            lines.append(f"**Atoms**: {', '.join(bond.atoms)}")
            lines.append("")
            lines.append(bond.explanation)
            lines.append("")
        lines += ["---", ""]

    # ── 5. エビデンス ──────────────────────────────────────────────────────────
    has_evidence = any(atom.get("pubmed_evidence") for atom in atoms)
    if has_evidence:
        lines += ["## 文献エビデンス", ""]
        for atom in atoms:
            papers = atom.get("pubmed_evidence", [])
            if not papers:
                continue
            lines.append(f"### {atom['name_en']} ({len(papers)} 件)")
            lines.append("")
            for p in papers[:3]:
                year   = p.get("year", "")
                pmid   = p.get("pmid", "")
                title  = p.get("title", "")[:120]
                journal = p.get("journal", "")
                authors = ", ".join(p.get("authors", [])[:2])
                url    = p.get("pubmed_url", f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/")
                lines.append(f"- **{year}** [{title}]({url})")
                lines.append(f"  {authors} — *{journal}*")
                lines.append("")
        lines += ["---", ""]

    if analysis.evidence_needed:
        lines += ["## 必要なエビデンス", ""]
        for ev in analysis.evidence_needed:
            lines.append(f"- {ev}")
        lines.append("")

    if analysis.experiment_suggestions:
        lines += ["## 実験提案", ""]
        for exp in analysis.experiment_suggestions:
            lines.append(f"- {exp}")
        lines.append("")

    # ── 6. 成分データ詳細 ─────────────────────────────────────────────────────
    has_compound = any(atom.get("compound") or atom.get("uniprot") for atom in atoms)
    if has_compound:
        lines += ["## 成分・化合物データ", ""]
        lines += ["| Atom | 分子式 | 分子量 (g/mol) | EC番号 | PubChem |"]
        lines += ["|---|---|---|---|---|"]
        for atom in atoms:
            compound = atom.get("compound", {})
            uniprot  = atom.get("uniprot", {})
            formula  = compound.get("molecular_formula", "—")
            mw       = compound.get("molecular_weight", "—")
            ec       = ", ".join(uniprot.get("ec_numbers", [])) or "—"
            cid_url  = compound.get("pubchem_url", "")
            cid_link = f"[CID {compound.get('pubchem_cid', '')}]({cid_url})" if cid_url else "—"
            lines.append(
                f"| {atom['name_en'][:30]} | {formula} | {mw} | {ec} | {cid_link} |"
            )
        lines += ["", "---", ""]

    # ── 7. IP / 商品化 ─────────────────────────────────────────────────────────
    if analysis.ip_potential:
        lines += ["## IP 可能性", "", analysis.ip_potential, ""]

    if analysis.product_direction:
        lines += ["## 商品化方向", ""]
        for pd in analysis.product_direction:
            lines.append(f"- {pd}")
        lines.append("")

    if analysis.process_direction:
        lines += ["## 加工・製造方向", ""]
        for pd in analysis.process_direction:
            lines.append(f"- {pd}")
        lines.append("")

    # ── 8. 調達情報 ────────────────────────────────────────────────────────────
    has_supplier = any(atom.get("supplier_info") for atom in atoms)
    if has_supplier or analysis.supplier_requirements:
        lines += ["## 調達・サプライヤー情報", ""]

        if has_supplier:
            lines += ["| Atom | 価格帯 | OEM剤形 | 主要サプライヤー | 日本サプライヤー |"]
            lines += ["|---|---|---|---|---|"]
            for atom in atoms:
                s = atom.get("supplier_info", {})
                if not s:
                    continue
                tier     = s.get("price_tier", "—")
                forms    = ", ".join(s.get("oem_forms", [])[:3])
                global_s = ", ".join(s.get("major_suppliers", [])[:2])
                japan_s  = ", ".join(s.get("japan_suppliers", [])[:2])
                lines.append(
                    f"| {atom['name_en'][:25]} | {tier} | {forms} | {global_s} | {japan_s} |"
                )
            lines.append("")

        if analysis.supplier_requirements:
            lines += ["### AI 推奨サプライヤー要件", ""]
            for sr in analysis.supplier_requirements:
                lines.append(f"- {sr}")
            lines.append("")

        lines += ["---", ""]

    # ── 8b. 市場トレンド・既存製品 ────────────────────────────────────────────
    has_market = any(atom.get("market_trends") or atom.get("existing_products") for atom in atoms)
    if has_market:
        lines += ["## 市場データ", ""]

        trend_rows = [(a, a["market_trends"]) for a in atoms if a.get("market_trends")]
        if trend_rows:
            lines += ["### Google Trends（直近12ヶ月 日本）", ""]
            lines += ["| Atom | JP関心度 | US関心度 | トレンド | ピーク月 |"]
            lines += ["|---|---|---|---|---|"]
            for atom, t in trend_rows:
                name  = atom["name_en"][:28]
                jp    = t.get("avg_interest_jp", 0)
                us    = t.get("avg_interest_us", 0)
                dir_s = {"rising": "📈 上昇", "stable": "➡️ 安定", "declining": "📉 下降"}.get(
                    t.get("trend_direction", ""), "—"
                )
                peak  = t.get("peak_month_jp", "—")
                lines.append(f"| {name} | {jp} | {us} | {dir_s} | {peak} |")
            lines.append("")

        off_rows = [(a, a["existing_products"]) for a in atoms if a.get("existing_products")]
        if off_rows:
            lines += ["### 既存製品（Open Food Facts）", ""]
            lines += ["| Atom | 製品数 | 主要カテゴリ | 主要販売国 |"]
            lines += ["|---|---|---|---|"]
            for atom, p in off_rows:
                name  = atom["name_en"][:28]
                total = p.get("total_count", 0)
                cats  = ", ".join(p.get("top_categories", [])[:2]) or "—"
                cntrs = ", ".join(p.get("top_countries", [])[:2]) or "—"
                lines.append(f"| {name} | {total:,} | {cats} | {cntrs} |")
            lines.append("")

        lines += ["---", ""]

    # ── 9. 規制・法規 ──────────────────────────────────────────────────────────
    atom_safety_notes = getattr(safety, "atom_safety_notes", [])
    if atom_safety_notes or analysis.regulatory_cautions:
        lines += ["## 規制・法規チェック", ""]

        if atom_safety_notes:
            lines += ["| Atom | GRAS | 日本区分 | エビデンス数 |"]
            lines += ["|---|---|---|---|"]
            for note in atom_safety_notes:
                name     = note.get("name", note.get("atom_id", ""))[:30]
                gras_s   = note.get("gras_status", "—")
                jp_s     = note.get("jp_status", "—")
                ev_count = note.get("evidence_count", 0)
                lines.append(f"| {name} | {gras_s} | {jp_s} | {ev_count} 件 |")
            lines.append("")

        if analysis.regulatory_cautions:
            lines += ["### AI 規制コメント", ""]
            for rc in analysis.regulatory_cautions:
                lines.append(f"- ⚖️ {rc}")
            lines.append("")

        lines += ["---", ""]

    # ── 10. 次のアクション ────────────────────────────────────────────────────
    if analysis.next_actions:
        lines += ["## 次のアクション", ""]
        for na in analysis.next_actions:
            lines.append(f"- [ ] {na}")
        lines.append("")
        lines += ["---", ""]

    # ── Disclaimer ─────────────────────────────────────────────────────────────
    lines += [
        "## Disclaimer",
        "",
        "このレポートは Formula Fuse Studio（AI）が生成した研究補助資料です。",
        "医療効果・安全性・特許性・法規制の確定的な判断ではありません。",
        "実際の開発・販売・特許出願・規制対応は必ず専門家（食品開発者・弁護士・薬剤師・規制専門家）に相談の上で行ってください。",
        "本ツールの AI 出力は参考情報であり、商業的・医療的判断の根拠として単独で使用してはいけません。",
        "",
        f"*Formula Fuse Studio v1.0 — {now}*",
    ]

    return "\n".join(lines)
