#!/usr/bin/env python3
"""
add_atoms_batch2.py — Atom マスタに第2バッチ（約65件）を追加

ingredient +26, microbe +7, condition +7, goal +10, enzyme +2 = 計 52件追加
"""
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).parent.parent
ATOMS_FILE = ROOT / "data" / "seed-atoms" / "food-bio-atoms.json"

NEW_ATOMS = [
    # ─── ingredient ───────────────────────────────────────────────────────────
    {
        "atom_id": "atom_resveratrol",
        "name_ja": "レスベラトロール",
        "name_en": "Resveratrol",
        "atom_type": "ingredient",
        "category": "polyphenol",
        "domain": "food_bio",
        "known_actions": ["antioxidant", "anti_inflammatory", "sirtuin_activation"],
        "possible_bonds": ["antioxidant_synergy", "bioavailability_enhancement", "anti_aging"],
        "risk_tags": ["drug_interaction_risk", "high_dose_caution"],
        "evidence_keywords": ["resveratrol antioxidant", "resveratrol sirtuin", "resveratrol bioavailability"],
        "regulatory_notes": [
            "Do not claim to treat or prevent specific diseases.",
            "High-dose supplementation may interact with blood thinners.",
        ],
        "process_keywords": ["grape skin extract", "Japanese knotweed", "microencapsulation"],
        "supplier_keywords": ["trans-resveratrol", "grape skin extract", "polygonum cuspidatum"],
        "gras": {"status": "unknown", "notes": "Generally recognized as safe at food levels; supplement doses under review"},
    },
    {
        "atom_id": "atom_quercetin",
        "name_ja": "ケルセチン",
        "name_en": "Quercetin",
        "atom_type": "ingredient",
        "category": "polyphenol",
        "domain": "food_bio",
        "known_actions": ["antioxidant", "anti_inflammatory", "mast_cell_stabilization"],
        "possible_bonds": ["antioxidant_synergy", "anti_allergy", "bioavailability_enhancement"],
        "risk_tags": ["drug_interaction_risk"],
        "evidence_keywords": ["quercetin anti-inflammatory", "quercetin antioxidant", "quercetin absorption"],
        "regulatory_notes": [
            "Do not claim to treat allergic diseases.",
            "May interact with certain antibiotics and cyclosporine.",
        ],
        "process_keywords": ["onion extract", "flavonoid", "encapsulation"],
        "supplier_keywords": ["quercetin dihydrate", "onion skin extract", "sophora japonica"],
        "gras": {"status": "unknown", "notes": "Widely consumed in diet; supplement status varies by jurisdiction"},
    },
    {
        "atom_id": "atom_alpha_lipoic_acid",
        "name_ja": "α-リポ酸",
        "name_en": "Alpha-lipoic acid (ALA)",
        "atom_type": "ingredient",
        "category": "coenzyme",
        "domain": "food_bio",
        "known_actions": ["antioxidant", "glucose_metabolism", "mitochondrial_support"],
        "possible_bonds": ["antioxidant_synergy", "energy_metabolism", "bioavailability_enhancement"],
        "risk_tags": ["drug_interaction_risk", "thiamine_interaction"],
        "evidence_keywords": ["alpha lipoic acid antioxidant", "ALA diabetes", "lipoic acid mitochondria"],
        "regulatory_notes": [
            "Do not claim to treat diabetes or neuropathy.",
            "May lower blood glucose; caution in diabetic patients.",
        ],
        "process_keywords": ["synthesis", "microencapsulation", "stabilization"],
        "supplier_keywords": ["R-alpha lipoic acid", "racemic ALA", "thioctic acid"],
        "compound": {
            "pubchem_cid": 864,
            "molecular_formula": "C8H14O2S2",
            "molecular_weight": "206.33",
            "smiles": "OC(=O)CCCC[C@@H]1CCSS1",
            "inchikey": "AGBQKNBQESQNJD-SSDOTTSWSA-N",
            "pubchem_url": "https://pubchem.ncbi.nlm.nih.gov/compound/864",
        },
    },
    {
        "atom_id": "atom_l_carnitine",
        "name_ja": "L-カルニチン",
        "name_en": "L-Carnitine",
        "atom_type": "ingredient",
        "category": "amino_acid_derivative",
        "domain": "food_bio",
        "known_actions": ["fat_metabolism", "energy_production", "sports_performance"],
        "possible_bonds": ["energy_metabolism", "fat_oxidation", "sports_synergy"],
        "risk_tags": [],
        "evidence_keywords": ["L-carnitine fat metabolism", "carnitine sports performance", "carnitine energy"],
        "regulatory_notes": [
            "Generally recognized as safe at recommended doses.",
            "Do not claim to treat cardiovascular disease.",
        ],
        "process_keywords": ["fermentation synthesis", "purification", "encapsulation"],
        "supplier_keywords": ["L-carnitine tartrate", "L-carnitine L-tartrate", "acetyl-L-carnitine"],
        "gras": {"status": "GRAS", "basis": "GRAS Notice 000339", "jp_status": "食品添加物相当（既存添加物）"},
        "compound": {
            "pubchem_cid": 10102,
            "molecular_formula": "C7H15NO3",
            "molecular_weight": "161.20",
            "smiles": "C[N+](C)(C)CC(CC([O-])=O)O",
            "inchikey": "PHIQHXFUZVPYII-ZCFIWIBFSA-N",
            "pubchem_url": "https://pubchem.ncbi.nlm.nih.gov/compound/10102",
        },
    },
    {
        "atom_id": "atom_vitamin_d",
        "name_ja": "ビタミンD（コレカルシフェロール）",
        "name_en": "Vitamin D3 (Cholecalciferol)",
        "atom_type": "ingredient",
        "category": "vitamin",
        "domain": "food_bio",
        "known_actions": ["bone_health", "immune_modulation", "calcium_absorption"],
        "possible_bonds": ["bone_mineral_synergy", "immune_support", "calcium_vitamin_d_synergy"],
        "risk_tags": ["vitamin_d_toxicity_risk_high_dose"],
        "evidence_keywords": ["vitamin D3 bone health", "cholecalciferol immune", "vitamin D deficiency"],
        "regulatory_notes": [
            "Upper limit: 4000 IU/day (adults) — do not exceed without medical supervision.",
            "Do not claim to treat osteoporosis without clinical evidence.",
        ],
        "process_keywords": ["UV irradiation", "lanolin extraction", "microencapsulation"],
        "supplier_keywords": ["cholecalciferol", "vitamin D3 oil", "vitamin D3 powder"],
        "gras": {"status": "GRAS", "basis": "21 CFR 184.1950", "jp_status": "栄養強化剤（食品添加物）"},
        "compound": {
            "pubchem_cid": 5280795,
            "molecular_formula": "C27H44O",
            "molecular_weight": "384.6",
            "smiles": "C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CCCC2=CC=C3C[C@@H](O)CCC3=C)C",
            "inchikey": "QYSXJUFSXHHAJI-XFEUOLMDSA-N",
            "pubchem_url": "https://pubchem.ncbi.nlm.nih.gov/compound/5280795",
        },
    },
    {
        "atom_id": "atom_vitamin_e",
        "name_ja": "ビタミンE（トコフェロール）",
        "name_en": "Vitamin E (Tocopherol)",
        "atom_type": "ingredient",
        "category": "vitamin",
        "domain": "food_bio",
        "known_actions": ["antioxidant", "membrane_protection", "immune_support"],
        "possible_bonds": ["antioxidant_synergy", "lipid_oxidation_prevention", "immune_support"],
        "risk_tags": ["anticoagulant_interaction_risk"],
        "evidence_keywords": ["tocopherol antioxidant", "vitamin E oxidative stress", "alpha tocopherol"],
        "regulatory_notes": [
            "Upper limit: 1000 mg/day alpha-tocopherol.",
            "Do not claim anticoagulant effects.",
        ],
        "process_keywords": ["vegetable oil extraction", "distillation", "microencapsulation"],
        "supplier_keywords": ["d-alpha tocopherol", "mixed tocopherols", "tocopherol acetate"],
        "gras": {"status": "GRAS", "basis": "21 CFR 182.3890", "jp_status": "栄養強化剤（食品添加物）"},
    },
    {
        "atom_id": "atom_vitamin_b12",
        "name_ja": "ビタミンB12（シアノコバラミン）",
        "name_en": "Vitamin B12 (Cyanocobalamin)",
        "atom_type": "ingredient",
        "category": "vitamin",
        "domain": "food_bio",
        "known_actions": ["nerve_function", "red_blood_cell_formation", "homocysteine_reduction"],
        "possible_bonds": ["energy_metabolism", "neurological_support", "homocysteine_metabolism"],
        "risk_tags": [],
        "evidence_keywords": ["vitamin B12 deficiency", "cobalamin nerve", "B12 vegan"],
        "regulatory_notes": [
            "Essential for vegans and vegetarians.",
            "Do not claim to treat pernicious anemia without medical supervision.",
        ],
        "process_keywords": ["fermentation synthesis", "bacterial production", "purification"],
        "supplier_keywords": ["cyanocobalamin", "methylcobalamin", "adenosylcobalamin"],
        "gras": {"status": "GRAS", "basis": "21 CFR 184.1945", "jp_status": "栄養強化剤（食品添加物）"},
        "compound": {
            "pubchem_cid": 44176380,
            "molecular_formula": "C63H88CoN14O14P",
            "molecular_weight": "1355.4",
            "smiles": None,
            "inchikey": "AGVAZMGAQJOSFJ-ZHACJKMWSA-N",
            "pubchem_url": "https://pubchem.ncbi.nlm.nih.gov/compound/44176380",
        },
    },
    {
        "atom_id": "atom_folic_acid",
        "name_ja": "葉酸（フォリック酸）",
        "name_en": "Folic acid",
        "atom_type": "ingredient",
        "category": "vitamin",
        "domain": "food_bio",
        "known_actions": ["cell_division", "neural_tube_development", "homocysteine_reduction"],
        "possible_bonds": ["prenatal_nutrition", "energy_metabolism", "homocysteine_metabolism"],
        "risk_tags": ["b12_masking_risk"],
        "evidence_keywords": ["folic acid neural tube", "folate pregnancy", "folic acid homocysteine"],
        "regulatory_notes": [
            "Critical for pregnant women: 400–800 mcg/day.",
            "High doses may mask B12 deficiency.",
            "Upper limit: 1000 mcg synthetic folic acid/day.",
        ],
        "process_keywords": ["chemical synthesis", "fortification", "tablet formulation"],
        "supplier_keywords": ["folic acid USP", "pteroylglutamic acid", "L-methylfolate"],
        "gras": {"status": "GRAS", "basis": "21 CFR 184.1304", "jp_status": "栄養強化剤（食品添加物）"},
        "compound": {
            "pubchem_cid": 6037,
            "molecular_formula": "C19H19N7O6",
            "molecular_weight": "441.4",
            "smiles": "Nc1nc2ncc(CNc3ccc(cc3)C(=O)N[C@@H](CCC(O)=O)C(O)=O)nc2c(=O)[nH]1",
            "inchikey": "OVBPIULPVIDEAO-LBPRGKRZSA-N",
            "pubchem_url": "https://pubchem.ncbi.nlm.nih.gov/compound/6037",
        },
    },
    {
        "atom_id": "atom_calcium",
        "name_ja": "カルシウム",
        "name_en": "Calcium",
        "atom_type": "ingredient",
        "category": "mineral",
        "domain": "food_bio",
        "known_actions": ["bone_health", "muscle_contraction", "nerve_transmission"],
        "possible_bonds": ["bone_mineral_synergy", "calcium_vitamin_d_synergy", "mineral_interaction"],
        "risk_tags": ["hypercalcemia_risk_high_dose"],
        "evidence_keywords": ["calcium bone density", "calcium osteoporosis", "calcium supplement"],
        "regulatory_notes": [
            "Upper limit: 2500 mg/day (adults).",
            "Do not claim to treat osteoporosis without clinical evidence.",
            "Absorption enhanced by vitamin D.",
        ],
        "process_keywords": ["dairy source", "limestone mineral", "microencapsulation"],
        "supplier_keywords": ["calcium carbonate", "calcium citrate", "calcium gluconate", "milk calcium"],
        "gras": {"status": "GRAS", "basis": "21 CFR 184.1191", "jp_status": "栄養強化剤（食品添加物）"},
        "compound": {
            "pubchem_cid": 5460341,
            "molecular_formula": "Ca",
            "molecular_weight": "40.08",
            "smiles": "[Ca]",
            "inchikey": "OYPRJOBELJOOCE-UHFFFAOYSA-N",
            "pubchem_url": "https://pubchem.ncbi.nlm.nih.gov/compound/5460341",
        },
    },
    {
        "atom_id": "atom_selenium",
        "name_ja": "セレン",
        "name_en": "Selenium",
        "atom_type": "ingredient",
        "category": "mineral",
        "domain": "food_bio",
        "known_actions": ["antioxidant", "thyroid_function", "immune_support"],
        "possible_bonds": ["antioxidant_synergy", "thyroid_support", "immune_support"],
        "risk_tags": ["selenium_toxicity_risk", "narrow_therapeutic_window"],
        "evidence_keywords": ["selenium antioxidant", "selenium thyroid", "selenoprotein"],
        "regulatory_notes": [
            "Upper limit: 400 mcg/day — narrow therapeutic window.",
            "Do not exceed recommended daily amounts.",
            "Do not claim to treat thyroid disease.",
        ],
        "process_keywords": ["yeast fermentation", "inorganic selenium", "selenomethionine"],
        "supplier_keywords": ["selenium yeast", "selenomethionine", "sodium selenate"],
        "gras": {"status": "GRAS", "basis": "21 CFR 184.1(a)", "jp_status": "栄養強化剤（食品添加物）"},
    },
    {
        "atom_id": "atom_beta_glucan",
        "name_ja": "β-グルカン",
        "name_en": "Beta-glucan",
        "atom_type": "ingredient",
        "category": "dietary_fiber",
        "domain": "food_bio",
        "known_actions": ["cholesterol_reduction", "immune_modulation", "blood_sugar_control"],
        "possible_bonds": ["prebiotic_effect", "cholesterol_binding", "immune_support"],
        "risk_tags": [],
        "evidence_keywords": ["beta glucan cholesterol", "oat beta glucan immunity", "beta glucan gut"],
        "regulatory_notes": [
            "FDA-approved health claim: 3g/day oat beta-glucan may reduce heart disease risk.",
            "Do not claim to treat hypercholesterolemia without clinical evidence.",
        ],
        "process_keywords": ["oat extraction", "yeast cell wall", "fermentation"],
        "supplier_keywords": ["oat beta glucan", "yeast beta 1,3/1,6 glucan", "barley beta glucan"],
        "gras": {"status": "GRAS", "basis": "21 CFR 172.891 (oat beta-glucan)", "jp_status": "食品（機能性表示食品対象）"},
    },
    {
        "atom_id": "atom_gos",
        "name_ja": "ガラクトオリゴ糖（GOS）",
        "name_en": "Galactooligosaccharides (GOS)",
        "atom_type": "ingredient",
        "category": "prebiotic_oligosaccharide",
        "domain": "food_bio",
        "known_actions": ["prebiotic", "bifidobacterium_growth", "immune_modulation"],
        "possible_bonds": ["prebiotic_effect", "gut_microbiome_support", "synbiotic_bond"],
        "risk_tags": [],
        "evidence_keywords": ["galactooligosaccharides prebiotic", "GOS Bifidobacterium", "GOS infant formula"],
        "regulatory_notes": [
            "Generally recognized as safe.",
            "Widely used in infant formula.",
        ],
        "process_keywords": ["lactose enzymatic synthesis", "lactase transglycosylation", "spray drying"],
        "supplier_keywords": ["GOS syrup", "Bimuno", "Vivinal GOS"],
        "gras": {"status": "GRAS", "basis": "GRAS Notice 000800", "jp_status": "食品添加物（既存添加物）"},
    },
    {
        "atom_id": "atom_soy_isoflavone",
        "name_ja": "大豆イソフラボン",
        "name_en": "Soy isoflavones",
        "atom_type": "ingredient",
        "category": "polyphenol",
        "domain": "food_bio",
        "known_actions": ["phytoestrogen", "bone_health", "antioxidant"],
        "possible_bonds": ["hormone_modulation", "bone_mineral_synergy", "antioxidant_synergy"],
        "risk_tags": ["hormone_sensitive_cancer_caution", "thyroid_interaction_risk"],
        "evidence_keywords": ["soy isoflavone bone", "genistein phytoestrogen", "isoflavone menopause"],
        "regulatory_notes": [
            "Caution in hormone-sensitive cancers (breast, uterine).",
            "May interfere with thyroid medication.",
            "Japan: max 30 mg/day isoflavone aglycone equivalent for supplements.",
        ],
        "process_keywords": ["soybean extraction", "isoflavone purification", "aglycone conversion"],
        "supplier_keywords": ["soy isoflavone extract", "genistein", "daidzein", "equol"],
        "gras": {"status": "unknown", "jp_status": "食品（機能性表示食品対象・上限設定あり）"},
    },
    {
        "atom_id": "atom_lactoferrin",
        "name_ja": "ラクトフェリン",
        "name_en": "Lactoferrin",
        "atom_type": "ingredient",
        "category": "dairy_protein",
        "domain": "food_bio",
        "known_actions": ["antimicrobial", "immune_modulation", "iron_transport"],
        "possible_bonds": ["antimicrobial_bond", "immune_support", "iron_metabolism"],
        "risk_tags": ["dairy_allergen"],
        "evidence_keywords": ["lactoferrin antimicrobial", "lactoferrin immunity", "bovine lactoferrin"],
        "regulatory_notes": [
            "Derived from bovine milk — declare allergen.",
            "Do not claim to treat infections.",
        ],
        "process_keywords": ["whey fractionation", "ion exchange chromatography", "spray drying"],
        "supplier_keywords": ["bovine lactoferrin", "apo-lactoferrin", "holo-lactoferrin"],
        "gras": {"status": "GRAS", "basis": "GRAS Notice 000325", "jp_status": "食品（既存添加物類似）"},
    },
    {
        "atom_id": "atom_casein",
        "name_ja": "カゼイン",
        "name_en": "Casein",
        "atom_type": "ingredient",
        "category": "dairy_protein",
        "domain": "food_bio",
        "known_actions": ["protein_source", "slow_release_protein", "calcium_carrier"],
        "possible_bonds": ["protein_degradation", "calcium_binding", "slow_digestion"],
        "risk_tags": ["dairy_allergen", "milk_protein_allergy"],
        "evidence_keywords": ["casein slow digestion", "micellar casein protein", "casein calcium"],
        "regulatory_notes": [
            "Declare as milk allergen.",
            "Do not claim safe for milk-allergic individuals.",
        ],
        "process_keywords": ["acid precipitation", "rennet coagulation", "micellar casein"],
        "supplier_keywords": ["micellar casein", "casein hydrolysate", "calcium caseinate", "sodium caseinate"],
        "gras": {"status": "GRAS", "basis": "21 CFR 184.1215", "jp_status": "食品素材"},
    },
    {
        "atom_id": "atom_lutein",
        "name_ja": "ルテイン",
        "name_en": "Lutein",
        "atom_type": "ingredient",
        "category": "carotenoid",
        "domain": "food_bio",
        "known_actions": ["eye_health", "macular_protection", "antioxidant"],
        "possible_bonds": ["antioxidant_synergy", "eye_health_support", "carotenoid_synergy"],
        "risk_tags": [],
        "evidence_keywords": ["lutein macular degeneration", "lutein zeaxanthin eye", "lutein blue light"],
        "regulatory_notes": [
            "Generally recognized as safe up to 20 mg/day.",
            "Do not claim to treat macular degeneration.",
        ],
        "process_keywords": ["marigold flower extraction", "saponification", "microencapsulation"],
        "supplier_keywords": ["marigold extract lutein", "FloraGLO lutein", "Lutemax"],
        "gras": {"status": "GRAS", "basis": "GRAS Notice 000140", "jp_status": "食品（機能性表示食品対象）"},
        "compound": {
            "pubchem_cid": 5281243,
            "molecular_formula": "C40H56O2",
            "molecular_weight": "568.9",
            "smiles": "OC1CC(=C(/C=C/C(=C/C=C/C(=C/C=C/C=C(\\C)/C=C/C=C(\\C)/C=C/[C@@H]2CC(O)CC(C)(C)2)\\C)\\C)C(C)(C)CC1",
            "inchikey": "KBPHJBAIARWVSC-RGWQACMPSA-N",
            "pubchem_url": "https://pubchem.ncbi.nlm.nih.gov/compound/5281243",
        },
    },
    {
        "atom_id": "atom_nattokinase",
        "name_ja": "ナットウキナーゼ",
        "name_en": "Nattokinase",
        "atom_type": "ingredient",
        "category": "functional_protein",
        "domain": "food_bio",
        "known_actions": ["fibrinolytic", "blood_circulation", "thrombolysis"],
        "possible_bonds": ["cardiovascular_support", "blood_flow_improvement", "enzyme_activity"],
        "risk_tags": ["anticoagulant_interaction_risk", "surgery_caution"],
        "evidence_keywords": ["nattokinase fibrinolytic", "nattokinase blood pressure", "natto cardiovascular"],
        "regulatory_notes": [
            "Do not use with anticoagulant medications without medical supervision.",
            "Stop 2 weeks before surgery.",
            "Do not claim to treat cardiovascular disease.",
        ],
        "process_keywords": ["Bacillus subtilis fermentation", "natto fermentation", "enzyme extraction"],
        "supplier_keywords": ["nattokinase NSK-SD", "Bacillus subtilis natto", "nattokinase FU"],
        "gras": {"status": "unknown", "jp_status": "食品（機能性表示食品対象）"},
    },
    {
        "atom_id": "atom_spirulina",
        "name_ja": "スピルリナ",
        "name_en": "Spirulina",
        "atom_type": "ingredient",
        "category": "algae",
        "domain": "food_bio",
        "known_actions": ["protein_source", "antioxidant", "immune_modulation", "anti_inflammatory"],
        "possible_bonds": ["antioxidant_synergy", "immune_support", "protein_source_bond"],
        "risk_tags": ["heavy_metal_contamination_risk", "autoimmune_caution"],
        "evidence_keywords": ["spirulina antioxidant", "spirulina protein", "spirulina immune"],
        "regulatory_notes": [
            "Test for heavy metals (lead, mercury, arsenic) — contamination risk.",
            "Caution in autoimmune diseases.",
            "Do not claim to treat anemia without clinical evidence.",
        ],
        "process_keywords": ["photobioreactor cultivation", "spray drying", "tablet compression"],
        "supplier_keywords": ["Arthrospira platensis", "spirulina powder", "spirulina tablets"],
        "gras": {"status": "GRAS", "basis": "21 CFR 73.530 (color)", "jp_status": "食品素材"},
    },
    {
        "atom_id": "atom_chlorella",
        "name_ja": "クロレラ",
        "name_en": "Chlorella",
        "atom_type": "ingredient",
        "category": "algae",
        "domain": "food_bio",
        "known_actions": ["detoxification", "immune_support", "chlorophyll_source"],
        "possible_bonds": ["detox_support", "immune_support", "heavy_metal_chelation"],
        "risk_tags": ["heavy_metal_contamination_risk", "drug_interaction_warfarin"],
        "evidence_keywords": ["chlorella detox", "chlorella heavy metal", "chlorella immune"],
        "regulatory_notes": [
            "Test for heavy metals.",
            "High vitamin K content — caution with warfarin.",
            "Do not claim to detoxify heavy metals without clinical evidence.",
        ],
        "process_keywords": ["photobioreactor cultivation", "cell wall disruption", "spray drying"],
        "supplier_keywords": ["Chlorella vulgaris", "broken cell wall chlorella", "chlorella powder"],
        "gras": {"status": "unknown", "jp_status": "食品素材（健康食品として流通）"},
    },
    {
        "atom_id": "atom_gla",
        "name_ja": "γ-リノレン酸（GLA）",
        "name_en": "Gamma-linolenic acid (GLA)",
        "atom_type": "ingredient",
        "category": "fatty_acid",
        "domain": "food_bio",
        "known_actions": ["anti_inflammatory", "skin_barrier", "prostaglandin_E1_precursor"],
        "possible_bonds": ["anti_inflammatory_synergy", "skin_health", "omega6_balance"],
        "risk_tags": ["drug_interaction_risk", "seizure_threshold_caution"],
        "evidence_keywords": ["gamma linolenic acid atopic", "GLA inflammation", "evening primrose GLA"],
        "regulatory_notes": [
            "Caution in patients with seizure disorders.",
            "May interact with blood-thinning medications.",
        ],
        "process_keywords": ["evening primrose extraction", "borage oil", "black currant seed oil"],
        "supplier_keywords": ["evening primrose oil", "borage oil", "black currant seed oil", "GLA concentrate"],
        "gras": {"status": "unknown", "jp_status": "食品素材"},
    },
    {
        "atom_id": "atom_black_ginger",
        "name_ja": "黒ショウガ（ブラックジンジャー）",
        "name_en": "Black ginger (Kaempferia parviflora)",
        "atom_type": "ingredient",
        "category": "plant_extract",
        "domain": "food_bio",
        "known_actions": ["energy_metabolism", "pde5_inhibition", "anti_fatigue"],
        "possible_bonds": ["energy_metabolism", "sports_synergy", "circulation_support"],
        "risk_tags": ["drug_interaction_risk"],
        "evidence_keywords": ["kaempferia parviflora sports", "black ginger energy", "methoxyflavone"],
        "regulatory_notes": [
            "Do not claim to treat erectile dysfunction.",
            "Do not combine with PDE5 inhibitor medications.",
        ],
        "process_keywords": ["rhizome extraction", "ethanol extraction", "standardization"],
        "supplier_keywords": ["Kaempferia parviflora extract", "KPE", "black ginger extract 5,7-dimethoxyflavone"],
        "gras": {"status": "unknown", "jp_status": "食品（機能性表示食品対象）"},
    },
    {
        "atom_id": "atom_nac",
        "name_ja": "N-アセチルシステイン（NAC）",
        "name_en": "N-Acetyl Cysteine (NAC)",
        "atom_type": "ingredient",
        "category": "amino_acid_derivative",
        "domain": "food_bio",
        "known_actions": ["glutathione_precursor", "antioxidant", "mucolytic"],
        "possible_bonds": ["antioxidant_synergy", "detox_support", "glutathione_production"],
        "risk_tags": ["drug_interaction_risk", "fda_supplement_concern"],
        "evidence_keywords": ["N-acetyl cysteine glutathione", "NAC antioxidant", "NAC liver"],
        "regulatory_notes": [
            "FDA has raised concerns about marketing NAC as a dietary supplement.",
            "Do not claim to treat liver disease.",
            "Verify regulatory status in target market.",
        ],
        "process_keywords": ["chemical synthesis", "cysteine acetylation"],
        "supplier_keywords": ["NAC pharmaceutical grade", "N-acetyl-L-cysteine", "effervescent NAC"],
        "compound": {
            "pubchem_cid": 12035,
            "molecular_formula": "C5H9NO3S",
            "molecular_weight": "163.19",
            "smiles": "CC(=O)N[C@@H](CS)C(O)=O",
            "inchikey": "PWKSKIMOESPYIA-BYPYZUCNSA-N",
            "pubchem_url": "https://pubchem.ncbi.nlm.nih.gov/compound/12035",
        },
    },
    {
        "atom_id": "atom_berberine",
        "name_ja": "ベルベリン",
        "name_en": "Berberine",
        "atom_type": "ingredient",
        "category": "alkaloid",
        "domain": "food_bio",
        "known_actions": ["blood_sugar_control", "antimicrobial", "lipid_metabolism"],
        "possible_bonds": ["blood_sugar_support", "gut_microbiome_modulation", "lipid_metabolism"],
        "risk_tags": ["drug_interaction_risk", "pregnancy_contraindicated"],
        "evidence_keywords": ["berberine blood glucose", "berberine diabetes", "berberine AMPK"],
        "regulatory_notes": [
            "Contraindicated in pregnancy.",
            "May interact with cyclosporine, metformin, and warfarin.",
            "Do not claim to treat diabetes.",
        ],
        "process_keywords": ["goldenseal extraction", "barberry extraction", "purification"],
        "supplier_keywords": ["berberine HCl", "berberine hydrochloride", "barberry extract"],
        "compound": {
            "pubchem_cid": 2353,
            "molecular_formula": "C20H18NO4+",
            "molecular_weight": "336.4",
            "smiles": "COc1ccc2CC3=CC=C(OC)C(=O)C3=c2c1OC",
            "inchikey": "YBHILYKTIRIUTE-UHFFFAOYSA-N",
            "pubchem_url": "https://pubchem.ncbi.nlm.nih.gov/compound/2353",
        },
    },
    {
        "atom_id": "atom_psyllium",
        "name_ja": "サイリウム（オオバコ）",
        "name_en": "Psyllium husk",
        "atom_type": "ingredient",
        "category": "dietary_fiber",
        "domain": "food_bio",
        "known_actions": ["cholesterol_reduction", "bowel_regularity", "blood_sugar_control"],
        "possible_bonds": ["cholesterol_binding", "prebiotic_effect", "blood_sugar_support"],
        "risk_tags": ["choking_hazard_without_water", "drug_absorption_interference"],
        "evidence_keywords": ["psyllium cholesterol", "psyllium fiber bowel", "psyllium blood sugar"],
        "regulatory_notes": [
            "Must be taken with adequate water to avoid choking.",
            "Take medications 1–2 hours away from psyllium.",
            "FDA-approved health claim for soluble fiber and heart disease.",
        ],
        "process_keywords": ["Plantago ovata husk milling", "fiber concentration", "granulation"],
        "supplier_keywords": ["psyllium husk 98%", "ispaghula husk", "psyllium seed husk"],
        "gras": {"status": "GRAS", "basis": "21 CFR 184.1(a)", "jp_status": "食品素材"},
    },
    {
        "atom_id": "atom_trehalose",
        "name_ja": "トレハロース",
        "name_en": "Trehalose",
        "atom_type": "ingredient",
        "category": "saccharide",
        "domain": "food_bio",
        "known_actions": ["cryoprotection", "moisture_retention", "protein_stabilization"],
        "possible_bonds": ["texture_improvement", "stability_enhancement", "preservation_support"],
        "risk_tags": [],
        "evidence_keywords": ["trehalose cryoprotection", "trehalose food stability", "trehalose protein"],
        "regulatory_notes": [
            "Generally recognized as safe.",
            "Do not claim medical benefits.",
        ],
        "process_keywords": ["starch enzymatic conversion", "crystallization", "spray drying"],
        "supplier_keywords": ["trehalose food grade", "TREHA", "α,α-trehalose"],
        "gras": {"status": "GRAS", "basis": "GRAS Notice 000077", "jp_status": "食品添加物（既存添加物）"},
        "compound": {
            "pubchem_cid": 7427,
            "molecular_formula": "C12H22O11",
            "molecular_weight": "342.30",
            "smiles": "OC[C@H]1O[C@@](CO)(O[C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)[C@@H](O)[C@@H]1O",
            "inchikey": "HDTRYLNUVZCQOY-WSWWMNSNSA-N",
            "pubchem_url": "https://pubchem.ncbi.nlm.nih.gov/compound/7427",
        },
    },
    {
        "atom_id": "atom_ergothioneine",
        "name_ja": "エルゴチオネイン",
        "name_en": "Ergothioneine",
        "atom_type": "ingredient",
        "category": "amino_acid_derivative",
        "domain": "food_bio",
        "known_actions": ["antioxidant", "cytoprotection", "anti_aging"],
        "possible_bonds": ["antioxidant_synergy", "cellular_protection", "anti_aging_support"],
        "risk_tags": [],
        "evidence_keywords": ["ergothioneine antioxidant", "ergothioneine mushroom", "longevity vitamin"],
        "regulatory_notes": [
            "Generally recognized as safe at studied doses.",
            "Novel food ingredient — check regulatory status in target market.",
        ],
        "process_keywords": ["mushroom cultivation", "mycelium fermentation", "extraction purification"],
        "supplier_keywords": ["ergothioneine mushroom extract", "EGT", "Ovothiol"],
        "gras": {"status": "unknown", "jp_status": "食品素材（新規機能性成分として注目）"},
    },
    {
        "atom_id": "atom_spermidine",
        "name_ja": "スペルミジン",
        "name_en": "Spermidine",
        "atom_type": "ingredient",
        "category": "polyamine",
        "domain": "food_bio",
        "known_actions": ["autophagy_induction", "anti_aging", "cardioprotection"],
        "possible_bonds": ["anti_aging_support", "cellular_renewal", "autophagy_activation"],
        "risk_tags": [],
        "evidence_keywords": ["spermidine autophagy", "spermidine longevity", "polyamine aging"],
        "regulatory_notes": [
            "Novel functional ingredient — verify regulatory status.",
            "Do not claim to extend lifespan.",
        ],
        "process_keywords": ["wheat germ extraction", "fermentation production", "purification"],
        "supplier_keywords": ["wheat germ spermidine", "spermidine trihydrochloride", "SpermidineLIFE"],
        "gras": {"status": "unknown", "jp_status": "食品素材（研究段階）"},
    },

    # ─── microbe ──────────────────────────────────────────────────────────────
    {
        "atom_id": "atom_lb_acidophilus",
        "name_ja": "Lactobacillus acidophilus",
        "name_en": "Lactobacillus acidophilus",
        "atom_type": "microbe",
        "category": "lactic_acid_bacteria",
        "domain": "food_bio",
        "known_actions": ["lactic_acid_production", "lactose_digestion", "vaginal_health"],
        "possible_bonds": ["probiotic_bond", "lacto_fermentation", "gut_microbiome_support"],
        "risk_tags": ["immunocompromised_caution"],
        "evidence_keywords": ["Lactobacillus acidophilus probiotic", "L. acidophilus lactose", "acidophilus vaginal"],
        "regulatory_notes": [
            "QPS status in EU.",
            "Caution in severely immunocompromised patients.",
        ],
        "process_keywords": ["anaerobic fermentation", "freeze drying", "microencapsulation"],
        "supplier_keywords": ["L. acidophilus NCFM", "La-5", "DDS-1"],
        "gras": {"status": "GRAS", "basis": "QPS (EU)", "jp_status": "食品素材（プロバイオティクス）"},
    },
    {
        "atom_id": "atom_lb_rhamnosus",
        "name_ja": "Lactobacillus rhamnosus GG",
        "name_en": "Lactobacillus rhamnosus GG (LGG)",
        "atom_type": "microbe",
        "category": "lactic_acid_bacteria",
        "domain": "food_bio",
        "known_actions": ["antibiotic_associated_diarrhea_prevention", "immune_modulation", "gut_barrier"],
        "possible_bonds": ["probiotic_bond", "gut_microbiome_support", "immune_support"],
        "risk_tags": ["immunocompromised_caution"],
        "evidence_keywords": ["Lactobacillus rhamnosus GG diarrhea", "LGG immune", "LGG gut barrier"],
        "regulatory_notes": [
            "Most clinically studied probiotic strain.",
            "Caution in immunocompromised individuals.",
        ],
        "process_keywords": ["anaerobic fermentation", "freeze drying", "encapsulation"],
        "supplier_keywords": ["LGG Valio", "Lactobacillus rhamnosus GG ATCC 53103"],
        "gras": {"status": "GRAS", "basis": "GRAS Notice 000049", "jp_status": "食品素材（プロバイオティクス）"},
    },
    {
        "atom_id": "atom_bf_longum",
        "name_ja": "Bifidobacterium longum",
        "name_en": "Bifidobacterium longum",
        "atom_type": "microbe",
        "category": "bifidobacterium",
        "domain": "food_bio",
        "known_actions": ["bifidobacterium_colonization", "immune_modulation", "constipation_relief"],
        "possible_bonds": ["probiotic_bond", "prebiotic_synergy", "synbiotic_bond"],
        "risk_tags": ["immunocompromised_caution"],
        "evidence_keywords": ["Bifidobacterium longum probiotic", "B. longum gut", "bifidus longum immunity"],
        "regulatory_notes": [
            "QPS status in EU.",
            "Caution in immunocompromised patients.",
        ],
        "process_keywords": ["anaerobic fermentation", "freeze drying", "oxygen barrier packaging"],
        "supplier_keywords": ["B. longum BB536", "B. longum NCC3001", "Bifidobacterium longum powder"],
        "gras": {"status": "GRAS", "basis": "QPS (EU)", "jp_status": "食品素材（プロバイオティクス）"},
    },
    {
        "atom_id": "atom_lb_casei",
        "name_ja": "Lactobacillus casei Shirota",
        "name_en": "Lactobacillus casei Shirota",
        "atom_type": "microbe",
        "category": "lactic_acid_bacteria",
        "domain": "food_bio",
        "known_actions": ["gut_motility", "immune_modulation", "NK_cell_activation"],
        "possible_bonds": ["probiotic_bond", "immune_support", "gut_microbiome_support"],
        "risk_tags": ["immunocompromised_caution"],
        "evidence_keywords": ["L. casei Shirota immunity", "Yakult probiotic", "L. casei NK cell"],
        "regulatory_notes": [
            "Widely used in fermented dairy products (Yakult).",
            "Caution in immunocompromised patients.",
        ],
        "process_keywords": ["anaerobic fermentation", "milk medium", "continuous culture"],
        "supplier_keywords": ["L. casei Shirota", "Lactobacillus casei 01"],
        "gras": {"status": "GRAS", "basis": "QPS (EU)", "jp_status": "食品素材（特定保健用食品実績あり）"},
    },
    {
        "atom_id": "atom_clostridium_butyricum",
        "name_ja": "酪酸菌（宮入菌）",
        "name_en": "Clostridium butyricum (Miyairi 588)",
        "atom_type": "microbe",
        "category": "spore_forming_bacteria",
        "domain": "food_bio",
        "known_actions": ["butyric_acid_production", "gut_barrier_support", "intestinal_flora_normalization"],
        "possible_bonds": ["gut_microbiome_support", "short_chain_fatty_acid_production", "probiotic_bond"],
        "risk_tags": ["immunocompromised_caution"],
        "evidence_keywords": ["Clostridium butyricum butyrate", "Miyairi 588 gut", "C. butyricum IBD"],
        "regulatory_notes": [
            "Long history of safe use in Japan (OTC drug: Miyarisan).",
            "Caution in immunocompromised patients.",
        ],
        "process_keywords": ["anaerobic spore formation", "freeze drying", "tableting"],
        "supplier_keywords": ["Miyarisan", "Clostridium butyricum MIYAIRI 588", "宮入菌"],
        "gras": {"status": "unknown", "jp_status": "医薬品（第3類）および食品素材として流通"},
    },
    {
        "atom_id": "atom_pediococcus",
        "name_ja": "ペディオコッカス（Pediococcus acidilactici）",
        "name_en": "Pediococcus acidilactici",
        "atom_type": "microbe",
        "category": "lactic_acid_bacteria",
        "domain": "food_bio",
        "known_actions": ["bacteriocin_production", "fermentation", "food_preservation"],
        "possible_bonds": ["lacto_fermentation", "antimicrobial_bond", "food_biopreservation"],
        "risk_tags": [],
        "evidence_keywords": ["Pediococcus acidilactici fermentation", "pediocin bacteriocin", "Pediococcus probiotic"],
        "regulatory_notes": [
            "QPS status in EU.",
            "Widely used in meat fermentation and plant-based fermentation.",
        ],
        "process_keywords": ["homo-fermentation", "sausage fermentation", "plant fermentation"],
        "supplier_keywords": ["Pediococcus acidilactici MA18/5M", "Bactoferm"],
        "gras": {"status": "GRAS", "basis": "QPS (EU)", "jp_status": "食品素材"},
    },
    {
        "atom_id": "atom_bacillus_coagulans",
        "name_ja": "Bacillus coagulans",
        "name_en": "Bacillus coagulans",
        "atom_type": "microbe",
        "category": "spore_forming_bacteria",
        "domain": "food_bio",
        "known_actions": ["lactic_acid_production", "heat_stable_probiotic", "gut_health"],
        "possible_bonds": ["probiotic_bond", "gut_microbiome_support", "heat_stable_fermentation"],
        "risk_tags": ["immunocompromised_caution"],
        "evidence_keywords": ["Bacillus coagulans probiotic", "B. coagulans IBS", "spore probiotic heat stable"],
        "regulatory_notes": [
            "Heat-stable spore form — survives processing.",
            "Caution in immunocompromised patients.",
        ],
        "process_keywords": ["spore fermentation", "spray drying", "tablet incorporation"],
        "supplier_keywords": ["GanedenBC30", "Bacillus coagulans MTCC 5856", "LactoSpore"],
        "gras": {"status": "GRAS", "basis": "GRAS Notice 000049", "jp_status": "食品素材（プロバイオティクス）"},
    },

    # ─── condition ────────────────────────────────────────────────────────────
    {
        "atom_id": "cond_uv_irradiation",
        "name_ja": "UV照射",
        "name_en": "UV irradiation",
        "atom_type": "condition",
        "category": "irradiation_condition",
        "domain": "food_bio",
        "known_actions": ["sterilization", "vitamin_d_production", "melanin_reduction"],
        "possible_bonds": ["sterilization_bond", "vitamin_d_enhancement", "surface_treatment"],
        "risk_tags": ["uv_denaturation_risk", "nutrient_degradation_risk"],
        "evidence_keywords": ["UV sterilization food", "UV vitamin D mushroom", "UV photodegradation"],
        "regulatory_notes": [
            "UV for food sterilization is approved in many jurisdictions.",
            "Monitor vitamin degradation (riboflavin, folate sensitive to UV).",
        ],
        "process_keywords": ["UV-C sterilization", "UV-B vitamin D", "photoreactor"],
        "supplier_keywords": ["UV lamp food grade", "UV-C reactor", "UVB irradiation system"],
    },
    {
        "atom_id": "cond_ultrasound",
        "name_ja": "超音波処理",
        "name_en": "Ultrasonic treatment",
        "atom_type": "condition",
        "category": "physical_condition",
        "domain": "food_bio",
        "known_actions": ["emulsification", "extraction_enhancement", "microbial_reduction"],
        "possible_bonds": ["extraction_enhancement", "emulsification_bond", "bioavailability_enhancement"],
        "risk_tags": [],
        "evidence_keywords": ["ultrasound extraction", "sonication emulsification", "ultrasound food processing"],
        "regulatory_notes": [
            "Generally considered a non-thermal processing method.",
            "Monitor for free radical generation at high power.",
        ],
        "process_keywords": ["sonication", "ultrasound homogenization", "acoustic cavitation"],
        "supplier_keywords": ["ultrasonic processor", "sonication probe", "bath sonicator"],
    },
    {
        "atom_id": "cond_72h_fermentation",
        "name_ja": "72h発酵",
        "name_en": "72-hour fermentation",
        "atom_type": "condition",
        "category": "time_condition",
        "domain": "food_bio",
        "known_actions": ["extended_fermentation", "complex_flavor_development", "deep_acidification"],
        "possible_bonds": ["fermentation_bond", "flavor_development", "protein_hydrolysis"],
        "risk_tags": ["over_acidification_risk", "off_flavor_risk"],
        "evidence_keywords": ["long fermentation acidification", "72 hour fermentation flavor", "extended fermentation"],
        "regulatory_notes": [
            "Monitor pH to prevent over-acidification.",
            "Ensure temperature control throughout.",
        ],
        "process_keywords": ["long fermentation", "sourdough", "aged fermented food"],
        "supplier_keywords": [],
    },
    {
        "atom_id": "cond_microwave",
        "name_ja": "マイクロ波処理",
        "name_en": "Microwave treatment",
        "atom_type": "condition",
        "category": "thermal_condition",
        "domain": "food_bio",
        "known_actions": ["rapid_heating", "sterilization", "enzyme_inactivation"],
        "possible_bonds": ["rapid_sterilization", "texture_modification", "enzyme_inactivation"],
        "risk_tags": ["non_uniform_heating_risk", "nutrient_degradation_risk"],
        "evidence_keywords": ["microwave food processing", "microwave sterilization", "microwave blanching"],
        "regulatory_notes": [
            "Ensure uniform temperature distribution for sterilization.",
            "Monitor for hot spots.",
        ],
        "process_keywords": ["microwave assisted extraction", "microwave pasteurization", "microwave drying"],
        "supplier_keywords": ["industrial microwave", "microwave oven food grade"],
    },
    {
        "atom_id": "cond_co2_atmosphere",
        "name_ja": "炭酸ガス（CO₂）環境",
        "name_en": "CO₂ / Modified atmosphere (MAP)",
        "atom_type": "condition",
        "category": "atmosphere_condition",
        "domain": "food_bio",
        "known_actions": ["preservation", "microbial_inhibition", "shelf_life_extension"],
        "possible_bonds": ["preservation_bond", "microbial_inhibition", "carbonation"],
        "risk_tags": [],
        "evidence_keywords": ["CO2 modified atmosphere packaging", "MAP preservation", "carbonation food"],
        "regulatory_notes": [
            "CO2 is approved as a food additive (E290) in EU.",
            "Ensure package integrity for MAP applications.",
        ],
        "process_keywords": ["modified atmosphere packaging", "MAP", "carbonation", "CO2 flushing"],
        "supplier_keywords": ["food grade CO2", "MAP packaging equipment"],
    },
    {
        "atom_id": "cond_60c",
        "name_ja": "60℃",
        "name_en": "60°C",
        "atom_type": "condition",
        "category": "temperature_condition",
        "domain": "food_bio",
        "known_actions": ["pasteurization", "enzyme_activation", "protein_denaturation"],
        "possible_bonds": ["pasteurization_bond", "enzyme_activation", "maillard_reaction"],
        "risk_tags": [],
        "evidence_keywords": ["60 degrees pasteurization", "low temperature long time LTLT", "enzyme activity 60"],
        "regulatory_notes": [
            "LTLT pasteurization: 63°C / 30 min standard.",
            "Monitor enzyme activity at this temperature.",
        ],
        "process_keywords": ["low temperature pasteurization", "LTLT", "sous vide"],
        "supplier_keywords": ["temperature controlled fermenter"],
    },
    {
        "atom_id": "cond_spray_drying",
        "name_ja": "スプレードライ（噴霧乾燥）",
        "name_en": "Spray drying",
        "atom_type": "condition",
        "category": "drying_condition",
        "domain": "food_bio",
        "known_actions": ["powder_production", "microencapsulation", "moisture_removal"],
        "possible_bonds": ["encapsulation_bond", "powder_formulation", "stability_enhancement"],
        "risk_tags": ["heat_sensitive_ingredient_caution", "oxidation_risk"],
        "evidence_keywords": ["spray drying encapsulation", "spray dried probiotics", "spray dry powder"],
        "regulatory_notes": [
            "Optimize inlet/outlet temperature for heat-sensitive ingredients.",
            "Protect from moisture post-drying.",
        ],
        "process_keywords": ["spray dryer", "atomization", "powder coating"],
        "supplier_keywords": ["spray dryer equipment", "encapsulation service"],
    },

    # ─── goal ─────────────────────────────────────────────────────────────────
    {
        "atom_id": "goal_blood_sugar",
        "name_ja": "血糖値サポート",
        "name_en": "Blood sugar management",
        "atom_type": "goal",
        "category": "metabolic_goal",
        "domain": "food_bio",
        "known_actions": ["glycemic_control", "insulin_sensitivity", "postprandial_glucose_reduction"],
        "possible_bonds": ["blood_sugar_support", "fiber_glucose_binding", "enzyme_inhibition"],
        "risk_tags": ["diabetes_drug_interaction_risk", "hypoglycemia_risk"],
        "evidence_keywords": ["blood sugar control supplement", "glycemic index reduction", "postprandial glucose"],
        "regulatory_notes": [
            "Do not claim to treat or manage diabetes.",
            "Do not combine with diabetes medication without medical supervision.",
            "Japan: 機能性表示食品 claims allowed with substantiation.",
        ],
        "process_keywords": ["functional food formulation", "fiber enrichment"],
        "supplier_keywords": [],
    },
    {
        "atom_id": "goal_cognitive",
        "name_ja": "認知機能サポート",
        "name_en": "Cognitive function support",
        "atom_type": "goal",
        "category": "neurological_goal",
        "domain": "food_bio",
        "known_actions": ["memory_support", "focus_enhancement", "neuroprotection"],
        "possible_bonds": ["neurological_support", "antioxidant_synergy", "blood_brain_barrier_support"],
        "risk_tags": ["dementia_claim_risk"],
        "evidence_keywords": ["cognitive function supplement", "memory brain health", "nootropic food"],
        "regulatory_notes": [
            "Do not claim to prevent or treat Alzheimer's or dementia.",
            "Japan: 機能性表示食品 'memory support' claims possible with RCT evidence.",
        ],
        "process_keywords": ["nootropic formulation", "DHA supplement", "phosphatidylserine"],
        "supplier_keywords": [],
    },
    {
        "atom_id": "goal_blood_pressure",
        "name_ja": "血圧サポート",
        "name_en": "Blood pressure support",
        "atom_type": "goal",
        "category": "cardiovascular_goal",
        "domain": "food_bio",
        "known_actions": ["vasodilation", "ace_inhibition", "endothelial_function"],
        "possible_bonds": ["cardiovascular_support", "peptide_ace_inhibition", "nitric_oxide_production"],
        "risk_tags": ["hypertension_drug_interaction_risk", "hypotension_risk"],
        "evidence_keywords": ["blood pressure supplement", "ACE inhibitor peptide", "antihypertensive food"],
        "regulatory_notes": [
            "Do not claim to treat hypertension.",
            "Do not combine with antihypertensive drugs without supervision.",
            "Japan: 特定保健用食品 claims require MHLW approval.",
        ],
        "process_keywords": ["peptide fermentation", "ACE inhibitory peptide", "nitric oxide"],
        "supplier_keywords": [],
    },
    {
        "atom_id": "goal_liver_support",
        "name_ja": "肝機能サポート",
        "name_en": "Liver function support",
        "atom_type": "goal",
        "category": "metabolic_goal",
        "domain": "food_bio",
        "known_actions": ["hepatoprotection", "detoxification_support", "bile_production"],
        "possible_bonds": ["detox_support", "antioxidant_synergy", "hepatoprotective_bond"],
        "risk_tags": ["hepatotoxic_ingredient_risk", "liver_disease_claim_risk"],
        "evidence_keywords": ["liver health supplement", "hepatoprotective", "liver detox"],
        "regulatory_notes": [
            "Do not claim to treat liver disease.",
            "Ensure all ingredients are tested for hepatotoxicity.",
        ],
        "process_keywords": ["hepatoprotective formulation", "silymarin", "TUDCA"],
        "supplier_keywords": [],
    },
    {
        "atom_id": "goal_weight_management",
        "name_ja": "体重管理・ダイエットサポート",
        "name_en": "Weight management support",
        "atom_type": "goal",
        "category": "metabolic_goal",
        "domain": "food_bio",
        "known_actions": ["appetite_regulation", "fat_metabolism", "thermogenesis"],
        "possible_bonds": ["fat_oxidation", "satiety_enhancement", "thermogenic_bond"],
        "risk_tags": ["stimulant_ingredient_risk", "eating_disorder_claim_risk"],
        "evidence_keywords": ["weight loss supplement", "fat burning food", "appetite suppression"],
        "regulatory_notes": [
            "Do not claim rapid or guaranteed weight loss.",
            "Avoid stimulant ingredients without safety data.",
            "Japan: 機能性表示食品 'body fat reduction' claims require RCT.",
        ],
        "process_keywords": ["thermogenic formulation", "fiber satiety", "protein satiety"],
        "supplier_keywords": [],
    },
    {
        "atom_id": "goal_allergy_reduction",
        "name_ja": "アレルギー低減",
        "name_en": "Allergen reduction",
        "atom_type": "goal",
        "category": "immunological_goal",
        "domain": "food_bio",
        "known_actions": ["allergen_hydrolysis", "immune_tolerance", "mast_cell_stabilization"],
        "possible_bonds": ["protein_degradation", "hypoallergenic_processing", "immune_modulation"],
        "risk_tags": ["allergen_claim_risk", "residual_allergen_risk"],
        "evidence_keywords": ["hypoallergenic food", "allergen reduction enzyme", "food allergy treatment"],
        "regulatory_notes": [
            "Do not claim 'allergen-free' without validated analytical testing.",
            "Do not claim to treat allergic disease.",
            "Any residual allergen must be declared.",
        ],
        "process_keywords": ["enzymatic hydrolysis", "fermentation allergen reduction", "hypoallergenic formulation"],
        "supplier_keywords": [],
    },
    {
        "atom_id": "goal_antimicrobial",
        "name_ja": "抗菌・静菌",
        "name_en": "Antimicrobial / biopreservation",
        "atom_type": "goal",
        "category": "preservation_goal",
        "domain": "food_bio",
        "known_actions": ["pathogen_inhibition", "shelf_life_extension", "natural_preservation"],
        "possible_bonds": ["antimicrobial_bond", "bacteriocin_production", "acid_preservation"],
        "risk_tags": ["antibiotic_resistance_claim_risk"],
        "evidence_keywords": ["food biopreservation", "natural antimicrobial", "bacteriocin food safety"],
        "regulatory_notes": [
            "Do not claim antibiotic activity.",
            "Validate antimicrobial efficacy with challenge testing.",
        ],
        "process_keywords": ["biopreservation", "natural antimicrobial", "hurdle technology"],
        "supplier_keywords": [],
    },
    {
        "atom_id": "goal_eye_health",
        "name_ja": "眼の健康サポート",
        "name_en": "Eye health support",
        "atom_type": "goal",
        "category": "sensory_goal",
        "domain": "food_bio",
        "known_actions": ["macular_protection", "blue_light_protection", "visual_acuity_support"],
        "possible_bonds": ["antioxidant_synergy", "carotenoid_synergy", "eye_health_support"],
        "risk_tags": [],
        "evidence_keywords": ["eye health supplement", "macular lutein zeaxanthin", "vision support"],
        "regulatory_notes": [
            "Do not claim to treat eye diseases.",
            "Japan: 機能性表示食品 claims for VDT eye fatigue allowed with evidence.",
        ],
        "process_keywords": ["carotenoid formulation", "microencapsulation", "softgel"],
        "supplier_keywords": [],
    },
    {
        "atom_id": "goal_energy_vitality",
        "name_ja": "エネルギー・活力サポート",
        "name_en": "Energy and vitality support",
        "atom_type": "goal",
        "category": "performance_goal",
        "domain": "food_bio",
        "known_actions": ["mitochondrial_support", "atp_production", "anti_fatigue"],
        "possible_bonds": ["energy_metabolism", "sports_synergy", "mitochondrial_support"],
        "risk_tags": ["stimulant_ingredient_risk"],
        "evidence_keywords": ["energy supplement", "anti fatigue food", "mitochondrial nutrition"],
        "regulatory_notes": [
            "Avoid stimulants (high-dose caffeine) without safety data.",
            "Do not claim to treat chronic fatigue syndrome.",
        ],
        "process_keywords": ["energy formulation", "B vitamin complex", "CoQ10 formulation"],
        "supplier_keywords": [],
    },
    {
        "atom_id": "goal_prebiotic_synbiotic",
        "name_ja": "シンバイオティクス（プレ＋プロバイオ）",
        "name_en": "Synbiotic formulation",
        "atom_type": "goal",
        "category": "functional_goal",
        "domain": "food_bio",
        "known_actions": ["combined_pre_probiotic_effect", "microbiome_modulation", "gut_health"],
        "possible_bonds": ["synbiotic_bond", "prebiotic_effect", "probiotic_bond"],
        "risk_tags": ["immunocompromised_caution"],
        "evidence_keywords": ["synbiotic probiotic prebiotic", "inulin Bifidobacterium synbiotic", "gut health synbiotic"],
        "regulatory_notes": [
            "Verify viability of probiotic throughout shelf life.",
            "Do not claim to treat GI disorders.",
        ],
        "process_keywords": ["synbiotic formulation", "co-fermentation", "encapsulation"],
        "supplier_keywords": [],
    },

    # ─── enzyme ───────────────────────────────────────────────────────────────
    {
        "atom_id": "enzyme_pectinase",
        "name_ja": "ペクチナーゼ",
        "name_en": "Pectinase",
        "atom_type": "enzyme",
        "category": "polysaccharide_hydrolase",
        "domain": "food_bio",
        "known_actions": ["pectin_degradation", "juice_clarification", "cell_wall_breakdown"],
        "possible_bonds": ["texture_modification", "juice_yield_improvement", "cell_wall_hydrolysis"],
        "risk_tags": [],
        "evidence_keywords": ["pectinase juice clarification", "pectinase fruit processing", "polygalacturonase"],
        "regulatory_notes": [
            "Approved food processing enzyme in most jurisdictions.",
            "Declare as processing aid where required.",
        ],
        "process_keywords": ["juice clarification", "mash treatment", "fruit processing"],
        "supplier_keywords": ["Pectinex Ultra", "pectinase Novozymes", "Rapidase"],
        "gras": {"status": "GRAS", "basis": "21 CFR 184.1387", "jp_status": "酵素（食品添加物）"},
    },
    {
        "atom_id": "enzyme_glucose_oxidase",
        "name_ja": "グルコースオキシダーゼ",
        "name_en": "Glucose oxidase",
        "atom_type": "enzyme",
        "category": "oxidoreductase",
        "domain": "food_bio",
        "known_actions": ["glucose_removal", "oxygen_removal", "shelf_life_extension"],
        "possible_bonds": ["oxidative_bond", "preservation_support", "dough_strengthening"],
        "risk_tags": [],
        "evidence_keywords": ["glucose oxidase baking", "glucose oxidase preservation", "H2O2 production enzyme"],
        "regulatory_notes": [
            "Used in baking, egg products, beverage preservation.",
            "Declare as processing aid where required.",
        ],
        "process_keywords": ["baking improver", "egg white glucose removal", "oxygen scavenging"],
        "supplier_keywords": ["glucose oxidase Novozymes", "Gluzyme", "glucose oxidase food grade"],
        "gras": {"status": "GRAS", "basis": "21 CFR 184.1387", "jp_status": "酵素（食品添加物）"},
    },
]


def main():
    atoms = json.loads(ATOMS_FILE.read_text(encoding="utf-8"))
    existing_ids = {a["atom_id"] for a in atoms}

    added = []
    skipped = []
    for atom in NEW_ATOMS:
        if atom["atom_id"] in existing_ids:
            skipped.append(atom["atom_id"])
        else:
            atoms.append(atom)
            added.append(atom["atom_id"])

    shutil.copy(ATOMS_FILE, str(ATOMS_FILE) + ".bak")
    ATOMS_FILE.write_text(json.dumps(atoms, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"✅ 追加: {len(added)} 件")
    for aid in added:
        a = next(x for x in atoms if x["atom_id"] == aid)
        print(f"  [{a['atom_type']:12}] {a['name_ja']} / {a['name_en']}")
    if skipped:
        print(f"⬜ スキップ（既存）: {len(skipped)} 件: {skipped}")
    print(f"\n合計 Atom 数: {len(atoms)}")


if __name__ == "__main__":
    main()
